### ISSUE TITLE
啥时候开赞赏码啊？

### ISSUE THREAD

**Issue by kunpeng9** [nczitzk/maison#1]
之前mailbrid邮件客户端发邮件有点问题，本来已经回了你的邮件的，结果发不出去，然后给搞丢了。
感觉还是这个方便些，直接写就完了。
![image](https://user-images.githubusercontent.com/44609485/102326807-d59be800-3fbf-11eb-96a5-403b304b025f.png)
类似这样的
https://getquicker.net/Sharedaction?code=4ba40435-c737-4aa3-136e-08d890deb233
![image](https://user-images.githubusercontent.com/44609485/102326879-eba9a880-3fbf-11eb-92b4-1c0a1ce1e279.png)

![image](https://user-images.githubusercontent.com/44609485/102327078-2ad7f980-3fc0-11eb-8bd1-3683072723fc.png)
像这样，点击就跳转图片，捐赠赞赏更加方便。

**Comment by nczitzk** [comment]
"Sponsor" button has been enabled 🤝
